### ISSUE TITLE
README

### ISSUE THREAD

**Issue by geoffwoollard** [flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1#27]
Please make suggestions for informative README.md files

- [x] landing page readme
- [x] notebook readme

**Comment by DavidHerreros** [comment]
I am making some suggestions [here](https://github.com/flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1/pull/29).

Let me know what you think!

**Comment by geoffwoollard** [comment]
https://github.com/flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1/pull/34
