### ISSUE TITLE
Make data downloaded/generated by testing consistent

### ISSUE THREAD

**Issue by DSilva27** [flatironinstitute/Cryo-EM-Heterogeneity-Challenge-1#41]
There are a couple of issues here. For example, there is a file that doesn't go to "tests/data/...". The results from distribution_to_distribution also don't go to tests. Something similar happens with the hash table generated by the preprocessing pipeline.

I made this fixes together with my power spectrum normalization PR (#15) since they are very small changes.

**Comment by geoffwoollard** [comment]
@DSilva27 can we close this?

**Comment by DSilva27** [comment]
Yes!
